{"DateTime":"3/30/2020 12:11:51 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","Exception":"Manual exception thrown.","ErrorCode":"-2146233088"}
{"DateTime":"3/30/2020 12:12:37 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","Exception":"Manual exception thrown.","ErrorCode":"-2146233088"}
{"DateTime":"3/30/2020 12:14:03 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","Exception":"Manual exception thrown.","ErrorCode":"-2146233088"}
{"DateTime":"3/30/2020 12:14:35 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","Exception":"Manual exception thrown.","ErrorCode":"-2146233088"}
{"DateTime":"3/30/2020 12:14:36 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","Exception":"Manual exception thrown.","ErrorCode":"-2146233088"}
{"DateTime":"3/30/2020 12:19:54 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","Exception":"Manual exception thrown.","ErrorCode":"-2146233088"}
{"DateTime":"3/30/2020 12:21:37 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","Exception":"Manual exception thrown.","ErrorCode":"-2146233088"}
{"DateTime":"3/30/2020 12:36:05 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","IsExceptionHandled":false,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\HomeController.cs","MethodName":"Index","LineNo":15,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.HomeController.Index() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\HomeController.cs:line 15\r\n   at lambda_method(Closure , ControllerBase , Object[] )\r\n   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)\r\n   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)"}
{"UniqueId":"2644a128-2421-40ad-aeca-a7f47c799751","DateTime":"3/30/2020 12:40:18 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","IsExceptionHandled":false,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\HomeController.cs","MethodName":"Index","LineNo":15,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.HomeController.Index() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\HomeController.cs:line 15\r\n   at lambda_method(Closure , ControllerBase , Object[] )\r\n   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)\r\n   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)"}
{"UniqueId":"481327c5-8321-4d1e-acf7-1c658c7c8b23","DateTime":"3/30/2020 12:41:15 PM","NameSpace":"ReshimgathiServices.Controllers.HomeController","IsExceptionHandled":false,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\HomeController.cs","MethodName":"Index","LineNo":14,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.HomeController.Index() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\HomeController.cs:line 14\r\n   at lambda_method(Closure , ControllerBase , Object[] )\r\n   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)\r\n   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)"}
{"UniqueId":"e1d923cc-7f9f-4861-a081-1f36a9a82128","DateTime":"3/30/2020 1:14:53 PM","NameSpace":"abc","IsExceptionHandled":false,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"Get","LineNo":18,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.Get() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 18\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
{"UniqueId":"54362583-ae0c-4617-8722-b596a45fbddf","DateTime":"3/30/2020 1:14:53 PM","NameSpace":"abc","IsExceptionHandled":false,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"Get","LineNo":18,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.Get() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 18\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
{"UniqueId":"c240146a-6568-4bef-9114-1923f583afb5","DateTime":"3/30/2020 1:15:27 PM","NameSpace":"abc","IsExceptionHandled":false,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"Get","LineNo":18,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.Get() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 18\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
{"UniqueId":"1897ff4c-91a7-4639-a9b9-4c8e0b636676","DateTime":"3/30/2020 1:38:33 PM","Controller":"Login","IsExceptionHandled":null,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"Get","LineNo":18,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.Get() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 18\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
{"UniqueId":"087205a8-7ecb-44b0-9556-4a3fd240db6f","DateTime":"3/30/2020 1:38:34 PM","Controller":"Login","IsExceptionHandled":null,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"Get","LineNo":18,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.Get() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 18\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
{"UniqueId":"46aa8ebd-1b6f-42c4-9d4a-5afd59b438fe","DateTime":"3/30/2020 1:51:46 PM","Namespace":"ReshimgathiServices.Controllers.LoginController","Controller":"Login","IsExceptionHandled":null,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"Get","LineNo":18,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.Get() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 18\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()","Host":"localhost","Version":"1.1"}
{"UniqueId":"6ee32dfb-1228-4528-9fc3-41911efc4270","DateTime":"3/30/2020 1:51:47 PM","Namespace":"ReshimgathiServices.Controllers.LoginController","Controller":"Login","IsExceptionHandled":null,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"Get","LineNo":18,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.Get() in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 18\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()","Host":"localhost","Version":"1.1"}
